### ISSUE TITLE
Link: /plugin:realtime

### ISSUE THREAD

**Issue by ravuthchaing** [Cacti/documentation#118] opened 2021-05-20 11:04 UTC
# Describe the link

Please describe what the old link was for use for and if possible what the new link should be.

## Old Link good

[ OLD LINK ] good 

## New Link very good

[ NEW LINK ] very good

**Comment by netniV** [comment] 2021-05-20 11:09
This is a duplicate of #117

**Closed by netniV** 2021-05-20 11:09 UTC
Labels: duplicate, old link
